### ISSUE TITLE
Introduction to Conda for (Data) Scientists

### ISSUE THREAD

**Issue by davidrpugh** [carpentrieslab/proposals#4]
I have developed a lesson that provides an introduction to Conda for (data) scientists. 

Conda is an open source package and environment management system that runs on Windows, macOS and Linux. Conda installs, runs, and updates packages and their dependencies. Conda easily creates, saves, loads, and switches between environments on your local computer. While Conda was created for Python programs it can package and distribute software for any languages such as R, Ruby, Lua, Scala, Java, JavaScript, C/ C++, FORTRAN. This lesson motivates the use of Conda as a development tool for building and sharing project specific software environments that facilitate reproducible (data) science workflows.

Link to the actual lesson:

https://kaust-vislab.github.io/introduction-to-conda-for-data-scientists/

Link to the repo:

https://github.com/kaust-vislab/introduction-to-conda-for-data-scientists

I teach this lesson to an audience of graduate students (MSc and PhD), post-docs, research scientists and faculty at KAUST.  I look forward to getting feedback from the community!

**Comment by ErinBecker** [comment]
Apologies @davidrpugh for the delayed response on this. We're still working on getting the reviewer system set up for the Lab and want to provide people with the opportunity to share their lessons in the interim, so are directing all lesson proposals and materials to the Incubator at this time. I've just sent you an email with instructions on how to get this lesson hosted in the Incubator. Please let me know what questions you have.

**Comment by tobyhodges** [comment]
Closing this as [the lesson has been included in the Incubator](https://github.com/carpentries-incubator/introduction-to-conda-for-data-scientists).
