### ISSUE TITLE
Programming with GAP

### ISSUE THREAD

**Issue by alex-konovalov** [carpentrieslab/proposals#5]
I would like to submit to the CarpentriesLab the lesson on Programming with GAP: 

- lesson website: http://alex-konovalov.github.io/gap-lesson/
- repository: https://github.com/alex-konovalov/gap-lesson
- wiki with details about where it has been taught and links to the feedback from sticky notes: https://github.com/alex-konovalov/gap-lesson/wiki
- published on Zenodo: https://doi.org/10.5281/zenodo.597073
- GAP: https://www.gap-system.org/

I wrote a couple of blog posts about this lesson some time ago:
- https://alex-konovalov.github.io/posts/2016/11/22/publishing-software-carpentry-lesson-on-gap/
- https://software-carpentry.org/blog/2016/11/gap-lesson.html

and also described it in my CarpentryCon talk this morning: https://doi.org/10.6084/m9.figshare.8330060.v1

**Comment by ErinBecker** [comment]
Apologies @alex-konovalov for the delayed response on this. I've just sent you an email with instructions on how to get this lesson hosted in the Incubator. Please let me know what questions you have.

**Comment by alex-konovalov** [comment]
Thanks @ErinBecker - it is now transferred to https://github.com/carpentries-incubator/gap-lesson. I will reply to your email now.

**Comment by ErinBecker** [comment]
Great! Thanks @alex-konovalov. I see it in the incubator and am closing this issue now.
